const KEY = 'gym-progress-v1';
const CATALOG = [
 ['Développé couché','Pectoraux'],['Développé couché haltères','Pectoraux'],['Développé incliné','Pectoraux'],['Écarté haltères','Pectoraux'],['Pompes','Pectoraux'],['Dips','Pectoraux'],
 ['Squat','Jambes'],['Front squat','Jambes'],['Presse à cuisses','Jambes'],['Fentes','Jambes'],['Soulevé de terre jambes tendues','Jambes'],['Leg curl','Jambes'],['Leg extension','Jambes'],['Mollets debout','Jambes'],
 ['Tractions','Dos'],['Tractions supination','Dos'],['Tirage vertical','Dos'],['Rowing barre','Dos'],['Rowing haltère','Dos'],['Rowing poulie','Dos'],['Soulevé de terre','Dos'],
 ['Développé militaire','Épaules'],['Élévations latérales','Épaules'],['Oiseau','Épaules'],['Face pull','Épaules'],
 ['Curl barre','Bras'],['Curl haltères','Bras'],['Curl marteau','Bras'],['Extension triceps poulie','Bras'],['Barre au front','Bras'],['Extension triceps haltère','Bras'],['Gainage','Abdominaux'],['Crunch','Abdominaux'],['Relevé de jambes','Abdominaux']
].map(([name,category], id) => ({id:`base-${id}`,name,category,builtin:true}));
let db = load(); let page = 'session'; let query = ''; let favoritesOnly = false; let metric = 'volume';
function load(){ try { return JSON.parse(localStorage.getItem(KEY)) || {sessions:[], customExercises:[], favorites:[]}; } catch { return {sessions:[],customExercises:[],favorites:[]}; } }
function save(){ localStorage.setItem(KEY,JSON.stringify(db)); }
function exercises(){ return [...CATALOG,...db.customExercises]; }
function current(){ return db.sessions.find(s=>s.open); }
function esc(s=''){ return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])); }
function vol(ex){ return ex.sets.reduce((t,s)=>t+(Number(s.reps)||0)*(Number(s.weight)||0),0); }
function startSession(){ if(!current()){ db.sessions.push({id:crypto.randomUUID(),number:(db.sessions.at(-1)?.number||0)+1,date:new Date().toISOString(),open:true,exercises:[]}); save(); } render(); }
function finish(){ const s=current(); if(!s) return; if(!s.exercises.length){ toast('Ajoute au moins un exercice.'); return; } s.open=false; save(); toast(`Séance ${s.number} enregistrée.`); render(); }
function render(){ const app=document.querySelector('#app'); app.innerHTML = page==='session'?renderSession():page==='exercises'?renderExercises():renderHistory(); bind(); }
function header(title,sub=''){ return `<header><div><h1>${title}</h1>${sub?`<div class="sub">${sub}</div>`:''}</div></header>`; }
function nav(){ return `<nav class="nav"><button data-page="session" class="${page==='session'?'active':''}">Séance</button><button data-page="exercises" class="${page==='exercises'?'active':''}">Exercices</button><button data-page="history" class="${page==='history'?'active':''}">Historique</button></nav>`; }
function renderSession(){ const s=current(); if(!s) return `${header('Progression','Simple, local, hors connexion')}<section class="card empty"><strong>Prêt pour la séance ?</strong><p>Crée une séance, choisis tes exercices et saisis tes séries.</p><br><button class="btn" data-action="start">Nouvelle séance</button></section>${nav()}`; return `${header(`Séance ${s.number}`,new Date(s.date).toLocaleDateString('fr-FR'))}<div id="session-list">${s.exercises.length?s.exercises.map(renderSessionExercise).join(''):`<section class="card empty"><strong>Aucun exercice</strong><p>Ajoute ton premier exercice.</p></section>`}</div><button class="btn secondary" data-action="pick">＋ Ajouter un exercice</button> <button class="btn" data-action="finish">Terminer la séance</button>${nav()}`; }
function renderSessionExercise(entry){ const ex=exercises().find(e=>e.id===entry.exerciseId)||{name:'Exercice supprimé'}; return `<section class="card"><div class="exercise-head"><div><h2>${esc(ex.name)}</h2><div class="sub">Volume : ${vol(entry).toLocaleString('fr-FR')} kg</div></div><button class="btn small secondary" data-action="graph" data-id="${entry.exerciseId}">Graphe</button></div><div class="labels"><span>#</span><span>Répétitions</span><span>Charge (kg)</span></div>${entry.sets.map((set,i)=>`<div class="set-row"><span class="set-num">${i+1}</span><input inputmode="decimal" type="number" min="0" step="1" value="${set.reps??''}" data-set="${entry.id}" data-field="reps" data-index="${i}" placeholder="reps"><input inputmode="decimal" type="number" step="0.5" value="${set.weight??''}" data-set="${entry.id}" data-field="weight" data-index="${i}" placeholder="kg"><button class="remove" data-action="remove-set" data-entry="${entry.id}" data-index="${i}" aria-label="Supprimer">×</button></div>`).join('')}<div class="quick"><button class="btn small secondary" data-action="add-set" data-entry="${entry.id}">＋ Série</button><label>Séries<input id="quick-n-${entry.id}" type="number" min="1" value="3"></label><label>Reps<input id="quick-r-${entry.id}" type="number" min="0" placeholder="10"></label><label>kg<input id="quick-w-${entry.id}" type="number" step="0.5" placeholder="80"></label><button class="btn small" data-action="quick" data-entry="${entry.id}">Ajouter</button></div><textarea class="note" placeholder="Ressenti facultatif…" data-note="${entry.id}">${esc(entry.note||'')}</textarea></section>`; }
function renderExercises(){ const list=exercises().filter(e=>(!favoritesOnly||db.favorites.includes(e.id)) && e.name.toLowerCase().includes(query.toLowerCase())); return `${header('Exercices','Recherche, favoris et créations personnelles')}<input class="search" id="search" placeholder="Rechercher un exercice" value="${esc(query)}"><div class="filter"><button data-action="favorites" class="${favoritesOnly?'active':''}">★ Favoris</button><button data-action="custom">＋ Créer un exercice</button></div><section class="card">${list.length?list.map(e=>`<div class="exercise-row"><button class="star" data-action="fav" data-id="${e.id}">${db.favorites.includes(e.id)?'★':'☆'}</button><div class="name">${esc(e.name)}<div class="category">${esc(e.category)}</div></div>${current()?`<button class="btn small" data-action="add-ex" data-id="${e.id}">Ajouter</button>`:`<button class="btn small secondary" data-action="graph" data-id="${e.id}">Graphe</button>`}</div>`).join(''):`<div class="empty">Aucun exercice trouvé.</div>`}</section>${nav()}`; }
function renderHistory(){ const done=db.sessions.filter(s=>!s.open).slice().reverse(); return `${header('Historique','Tes séances enregistrées')}<div class="top-actions"><button class="btn secondary" data-action="export">Exporter CSV</button><button class="btn secondary" data-action="import">Importer</button></div><input type="file" id="import-file" accept="application/json" hidden><section class="card" style="margin-top:13px">${done.length?done.map(s=>`<div class="history-item"><div><strong>Séance ${s.number}</strong><div class="category">${s.exercises.map(x=>esc(exercises().find(e=>e.id===x.exerciseId)?.name||'Exercice')).join(' · ')}</div></div><div class="right">${new Date(s.date).toLocaleDateString('fr-FR')}<br>${s.exercises.reduce((v,x)=>v+vol(x),0).toLocaleString('fr-FR')} kg</div></div>`).join(''):`<div class="empty"><strong>Pas encore de séance</strong><p>Ton historique apparaîtra ici.</p></div>`}</section><section class="card"><h2>Sauvegarde complète</h2><p class="sub">Pour changer de téléphone, exporte aussi une copie de sauvegarde.</p><br><button class="btn small secondary" data-action="backup">Télécharger la sauvegarde</button></section>${nav()}`; }
function bind(){ document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{page=b.dataset.page;render()}); document.querySelectorAll('[data-action]').forEach(b=>b.onclick=action); const search=document.querySelector('#search'); if(search) search.oninput=()=>{query=search.value; renderExercisesOnly();}; document.querySelectorAll('[data-set]').forEach(i=>i.oninput=updateSet); document.querySelectorAll('[data-note]').forEach(i=>i.oninput=()=>{const x=current().exercises.find(e=>e.id===i.dataset.note);x.note=i.value;save();}); const fi=document.querySelector('#import-file');if(fi)fi.onchange=importBackup; }
function renderExercisesOnly(){ const old=document.querySelector('#app'); old.innerHTML=renderExercises();bind(); document.querySelector('#search')?.focus(); }
function action(e){ const b=e.currentTarget, a=b.dataset.action; if(a==='start')startSession(); if(a==='finish')finish(); if(a==='pick'){page='exercises';render();} if(a==='fav'){const id=b.dataset.id,i=db.favorites.indexOf(id);i<0?db.favorites.push(id):db.favorites.splice(i,1);save();render();} if(a==='favorites'){favoritesOnly=!favoritesOnly;renderExercisesOnly();} if(a==='add-ex'){addExercise(b.dataset.id);page='session';render();} if(a==='add-set')addSet(b.dataset.entry); if(a==='remove-set')removeSet(b.dataset.entry,+b.dataset.index); if(a==='quick')quickAdd(b.dataset.entry); if(a==='custom')customModal(); if(a==='graph')graphModal(b.dataset.id); if(a==='export')exportCsv(); if(a==='backup')download('progression-sauvegarde.json',JSON.stringify(db,null,2),'application/json'); if(a==='import')document.querySelector('#import-file').click(); }
function addExercise(id){const s=current();if(!s)return; if(s.exercises.some(e=>e.exerciseId===id)){toast('Déjà ajouté à cette séance.');return;}s.exercises.push({id:crypto.randomUUID(),exerciseId:id,sets:[{reps:'',weight:''}],note:''});save();}
function addSet(id){const x=current().exercises.find(e=>e.id===id), last=x.sets.at(-1)||{};x.sets.push({reps:last.reps??'',weight:last.weight??''});save();render();}
function removeSet(id,i){const x=current().exercises.find(e=>e.id===id);if(x.sets.length>1)x.sets.splice(i,1);else x.sets[0]={reps:'',weight:''};save();render();}
function updateSet(e){const x=current().exercises.find(z=>z.id===e.target.dataset.set);x.sets[+e.target.dataset.index][e.target.dataset.field]=e.target.value;save();}
function quickAdd(id){const n=+document.querySelector(`#quick-n-${id}`).value||0,r=document.querySelector(`#quick-r-${id}`).value,w=document.querySelector(`#quick-w-${id}`).value;if(!n||r===''||w===''){toast('Indique séries, reps et kg.');return;} const x=current().exercises.find(e=>e.id===id); for(let i=0;i<n;i++)x.sets.push({reps:r,weight:w}); if(x.sets.length>n && x.sets[0].reps===''&&x.sets[0].weight==='')x.sets.shift();save();render();}
function customModal(){modal(`<div class="modal-head"><h2>Nouvel exercice</h2><button class="close" data-close>×</button></div><div class="form-group"><label>Nom</label><input id="custom-name" placeholder="Ex. Hip thrust" autofocus></div><div class="form-group"><label>Catégorie (facultatif)</label><input id="custom-cat" placeholder="Ex. Jambes"></div><button class="btn" id="save-custom">Créer</button>`);document.querySelector('#save-custom').onclick=()=>{const name=document.querySelector('#custom-name').value.trim(),category=document.querySelector('#custom-cat').value.trim()||'Personnalisé';if(!name){toast('Indique un nom.');return;}db.customExercises.push({id:crypto.randomUUID(),name,category});save();closeModal();render();};}
function graphModal(id){const ex=exercises().find(e=>e.id===id), points=db.sessions.filter(s=>!s.open).map(s=>{const item=s.exercises.find(x=>x.exerciseId===id);if(!item)return null;return {n:s.number,date:s.date,volume:vol(item),max:Math.max(...item.sets.map(x=>Number(x.weight)||0)),reps:item.sets.reduce((a,x)=>a+(Number(x.reps)||0),0)};}).filter(Boolean); modal(`<div class="modal-head"><div><h2>${esc(ex.name)}</h2><div class="sub">Progression par séance</div></div><button class="close" data-close>×</button></div><div class="metric-tabs"><button data-metric="volume" class="${metric==='volume'?'active':''}">Volume</button><button data-metric="max" class="${metric==='max'?'active':''}">Charge max</button><button data-metric="reps" class="${metric==='reps'?'active':''}">Répétitions</button></div>${points.length?chart(points):`<div class="empty">Pas encore de données pour cet exercice.</div>`}`);document.querySelectorAll('[data-metric]').forEach(b=>b.onclick=()=>{metric=b.dataset.metric;graphModal(id)});}
function chart(points){const max=Math.max(...points.map(p=>p[metric]),1), min=Math.min(...points.map(p=>p[metric]),0),range=Math.max(max-min,1); let html=`<div class="chart"><span class="axis-y" style="bottom:100%">${max.toLocaleString('fr-FR')}</span><span class="axis-y" style="bottom:0">${min.toLocaleString('fr-FR')}</span>`;points.forEach((p,i)=>{const x=points.length===1?50:i/(points.length-1)*100,y=(p[metric]-min)/range*100;html+=`<span class="point" title="Séance ${p.n}: ${p[metric]}" style="left:${x}%;bottom:${y}%"></span>`;if(i){const prev=points[i-1],px=points.length===1?50:(i-1)/(points.length-1)*100,py=(prev[metric]-min)/range*100,dx=x-px,dy=y-py;const width=Math.sqrt(dx*dx+dy*dy),angle=-Math.atan2(dy,dx)*180/Math.PI;html+=`<i class="chart-line" style="left:${px}%;bottom:${py}%;width:${width}%;transform:rotate(${angle}deg)"></i>`;}}); return html+`</div><div class="chart-x"><span>Séance ${points[0].n}</span><span>Séance ${points.at(-1).n}</span></div><p class="sub" style="margin-top:12px">${metric==='volume'?'kg soulevés au total':metric==='max'?'kg par barre ou haltère':'répétitions au total'} · ${points.length} séance(s)</p>`;}
function modal(content){document.body.insertAdjacentHTML('beforeend',`<div class="modal"><div class="modal-panel">${content}</div></div>`);document.querySelector('[data-close]')?.addEventListener('click',closeModal);}
function closeModal(){document.querySelector('.modal')?.remove();}
function exportCsv(){const rows=[['numero_seance','date','exercice','numero_serie','repetitions','charge_kg','ressenti']];db.sessions.filter(s=>!s.open).forEach(s=>s.exercises.forEach(x=>{const name=exercises().find(e=>e.id===x.exerciseId)?.name||'Exercice';x.sets.forEach((set,i)=>rows.push([s.number,new Date(s.date).toLocaleDateString('fr-CA'),name,i+1,set.reps,set.weight,x.note||'']));}));download('progression-musculation.csv','\uFEFF'+rows.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(';')).join('\n'),'text/csv;charset=utf-8');}
function download(name,data,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type}));a.download=name;a.click();URL.revokeObjectURL(a.href);}
function importBackup(e){const f=e.target.files[0];if(!f)return;const reader=new FileReader();reader.onload=()=>{try{const imported=JSON.parse(reader.result);if(!Array.isArray(imported.sessions))throw Error();db=imported;save();toast('Sauvegarde importée.');render();}catch{toast('Ce fichier de sauvegarde est invalide.');}};reader.readAsText(f);}
function toast(msg){document.querySelector('.toast')?.remove();document.body.insertAdjacentHTML('beforeend',`<div class="toast">${esc(msg)}</div>`);setTimeout(()=>document.querySelector('.toast')?.remove(),2200);}
if('serviceWorker' in navigator) navigator.serviceWorker.register('./sw.js'); render();
